### ISSUE TITLE
python3 not support?

### ISSUE THREAD

**Issue by yishenggudou** [sphinx-contrib/plantuml#10]
```
Collecting sphinxcontrib-plantuml
  Using cached sphinxcontrib-plantuml-0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/setuptools/__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/setuptools/extern/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 3017, in <module>
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 3003, in _call_aside
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 2577, in activate
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 2151, in declare_namespace
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 2091, in _handle_ns
      File "/Volumes/data/vpythons/python3/lib/python3.5/site-packages/setuptools-28.8.0-py3.5.egg/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gk/m7y8np8517l95tl2y4zkdzdh0000gn/T/pycharm-packaging/sphinxcontrib-plantuml/
```

**Comment by yuja** [comment]
Works for me. Guessing from the traceback, your Python enviroment
would be broken.

```
% python3 setup.py egg_info
running egg_info
writing sphinxcontrib_plantuml.egg-info/PKG-INFO
writing dependency_links to sphinxcontrib_plantuml.egg-info/dependency_links.txt
writing namespace_packages to sphinxcontrib_plantuml.egg-info/namespace_packages.txt
writing requirements to sphinxcontrib_plantuml.egg-info/requires.txt
writing top-level names to sphinxcontrib_plantuml.egg-info/top_level.txt
reading manifest file 'sphinxcontrib_plantuml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching 'LICENSE'
warning: no files found matching 'CHANGES.*'
writing manifest file 'sphinxcontrib_plantuml.egg-info/SOURCES.txt'
```

**Comment by yishenggudou** [comment]
@yuja 
yes 
Is my problem
